### ISSUE TITLE
itsmy.fyi - controlk9

### ISSUE THREAD

**Issue by jubssaez** [rishi-raj-jain/itsmy.fyi#180]
### itsmy.fyi Profile Data

```Markdown
---
slug: controlk9
name: Control Cães Farejadores
about: Nosso compromisso é proteger vidas, propriedades e infraestruturas críticas, garantindo um ambiente seguro e livre de ameaças para nossos clientes.
image: https://www.controlk9.com.br/logo.png
links: [["Nosso Site", "http://controlk9.com.br/"]]
socials: [["Instagram", "https://www.instagram.com/control_caes_farejadores"]], [["Facebook", "https://www.facebook.com/controlcaesfarejadores
"]], [["YouTube", "https://www.youtube.com/@ricardonewdog
"]], [["WhatsApp", "https://api.whatsapp.com/send/?phone=5511975569730&text&type=phone_number&app_absent=0"]], [["@ricardonewdog", "
https://www.instagram.com/ricardonewdog
"]]
og:
  image: https://www.controlk9.com.br/logo.png
background:
  image: https://volta.net/home/hero.png
---


The expected format for itsmy.fyi to parse your data would be:

## Required

slug: **required**, String (without quotes, newline, let's keep it simple!)
name: **required**, String (without quotes or newline)
image: **required**, String (without quotes or newline)
links: **required**, but can be empty array [], (examples: [["My Website", "https://rishi.app"], ["Web", "https://rishi.app", "https://rishi.app/static/favicon-image.jpg"]])
socials: **required**, but can be empty array [], (example: [["twitter", "https://twitter.com/rishi_raj_jain_"], ["linkedin", "https://linked.com/in/rishi-raj-jain"]])

## Optional

about: optional, String (without quotes or newline)
og:
    image: optional, String (without quotes or newline)
ga:
    enabled: boolean, true or false (without quotes or newline)
    configID: **required if enabled is true**, String (ex. "G-RANDOM")
background:
    color: optional, can be a String (ex. pink), Hexcode (ex. "#C1C1C1" with the quotes) or anything that background: CSS supports
    image: optional, an absolute URL
```

**Comment by rishi-raj-jain** [comment]
Bad luck! Here's what we found breaking in your data:

```markdown
end of the stream or a document separator is expected at line 7, column 79:
     ... .com/control_caes_farejadores"]], [["Facebook", "https://www.fac ... 
                                         ^
```

Feel free to edit the issue again in case you've already got a link, else please re-try by creating a [new issue](https://github.com/rishi-raj-jain/itsmy.fyi/issues/new?assignees=&labels=&template=itsyour.page-profile-data.yml&title=itsmy.fyi+-+%7BINSERT+NAME%7D+%28Optional%29) for now.

**Comment by rishi-raj-jain** [comment]
Hey can you close this issue and open a new one with the following data:

```
---
slug: controlk9
name: Control Cães Farejadores
about: Nosso compromisso é proteger vidas, propriedades e infraestruturas críticas, garantindo um ambiente seguro e livre de ameaças para nossos clientes.
image: https://www.controlk9.com.br/logo.png
links: [["Nosso Site", "http://controlk9.com.br/"]]
socials: [["Instagram", "https://www.instagram.com/control_caes_farejadores"]], [["Facebook", "https://www.facebook.com/controlcaesfarejadores"]], [["YouTube", "https://www.youtube.com/@ricardonewdog
"]], [["WhatsApp", "https://api.whatsapp.com/send/?phone=5511975569730&text&type=phone_number&app_absent=0"]], [["@ricardonewdog", "https://www.instagram.com/ricardonewdog"]]
og:
  image: https://www.controlk9.com.br/logo.png
background:
  image: https://volta.net/home/hero.png
---
```
